### ISSUE TITLE
Missing fraction scaling for snow temperature and conductivity

### ISSUE THREAD

**Issue by MartinDix** [ACCESS-NRI/CICE#3]
The ice temperature and conductivity are scaled by the ice fraction but snow fields aren't.

https://github.com/ACCESS-NRI/CICE/blob/044618c3e2b824b8d19ca12fadc5534716e27290/cicecore/drivers/access/cmeps/ice_import_export.F90#L2089-L2109

CM3 starts with ~ 20 cm of snow over the ice so this causes problems right away.

**Comment by kieranricardo** [comment]
fixed with https://github.com/ACCESS-NRI/CICE/commit/979f83e4b7bad7a7bbe3c1b771def0b3ddf296c0
